### ISSUE TITLE
Wrong coordinates with multiple knobs

### ISSUE THREAD

**Issue by Couiljer** [pavelkukov/react-dial-knob#2] opened 2020-04-14 16:29 UTC
Hi there, 

first thx for this package that is pretty well done. 
I'm having an issue with Knob components interaction in a list. I mapped a list that render for each list item a basic knob vertically aligned. The first knob works perfectly fine. 

However, If i click on  2nd, 3rd .... n knob, the value sets at the bottom of that knob. To reach the top of the knob I have to keep the mouse down and drag the cursor to the top of the first knob on the list. It seems that all click/drag coordinates are based on the first one. 

Does anyone know how to fix this ? Thx.

**Comment by pavelkukov** [comment] 2020-04-15 11:26
Hi @Couiljer ,
I've tried to reproduce this but without success. 
Are you using the latest version `1.1.3`?

**Comment by Couiljer** [comment] 2020-04-15 13:05
@pavelkukov yes I use that version. I realized that it works fine on normal list. The issues appears on a react-spring animated list component with their useSpring() hook. There might be some CSS or DOM related issues. I'll investigate. Thx for help !

**Comment by pavelkukov** [comment] 2020-04-15 14:08
If you can provide some reproduction code I will try to investigate and make it work with `react-spring`.

**Comment by pavelkukov** [comment] 2020-04-17 07:10
I'm closing this as it is not reproducible.
https://pavelkukov.github.io/react-dial-knob/?path=/story/knob-layout--multiple-knobs-and-positions-demo

**Comment by Couiljer** [comment] 2020-04-21 09:06
Thx for your Time @pavelkukov. I can't reproduce it on sandbox, can't find the difference.. However I see this warning in the console : `Warning: Cannot update a component (`MyKnobSkin`) while rendering a different component (`Knob`). To locate the bad setState() call inside `Knob`, follow the stack trace as described in https://fb.me/setstate-in-render`. 
I used your template for custom knob and it seems that this warn is thrown by  the angle state `   const [angle, setAngle] = useState(0)`

that's all I know (for now).

**Comment by pavelkukov** [comment] 2020-04-21 09:58
I've tried to reproduce the warning here: https://codepen.io/pavelkukov/pen/vYNXqEd?editors=0010
and here with a shared state: https://codepen.io/pavelkukov/pen/gOawNxZ?editors=0010
It worked without issues. 
Do you see the warning on the initial render or you see it while interacting?

**Comment by Couiljer** [comment] 2020-04-21 12:21
- It is at initial render
- I reproduced it. Just took the example I'm based on from react-spring / react-use-gesture and add in the list elements a Basic knob. You should see that the angle vector origin stays at first row.
https://codesandbox.io/s/draggable-list-tekzx?file=/src/index.js

**Comment by pavelkukov** [comment] 2020-04-21 12:47
Yep, I see it. Thank you!
I will take a look. Probably is due to translate3d style used to order rows.

**Closed as completed** 2020-04-21 14:46 UTC

**Comment by pavelkukov** [comment] 2020-04-21 15:08
Hi @Couiljer ,
I've fixed the issue with translate3d.
A new version (1.1.5) is available on NPM

Cheers,
Pavel

**Comment by Couiljer** [comment] 2020-04-21 16:01
@pavelkukov that works perfectly fine now ! awesome job, thanks for your time and reactivity !
